//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from f:/Apps/Stalker2Modding/Stalker2PakCfgMergeTool/Stalker2PakCfgMergeTool/grammar/Stalker2Cfg.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="Stalker2CfgParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IStalker2CfgVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="Stalker2CfgParser.cfg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCfg([NotNull] Stalker2CfgParser.CfgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Stalker2CfgParser.map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMap([NotNull] Stalker2CfgParser.MapContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Stalker2CfgParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPair([NotNull] Stalker2CfgParser.PairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Stalker2CfgParser.struct_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_pair([NotNull] Stalker2CfgParser.Struct_pairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Stalker2CfgParser.struct_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_ref([NotNull] Stalker2CfgParser.Struct_refContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Stalker2CfgParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] Stalker2CfgParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Stalker2CfgParser.key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKey([NotNull] Stalker2CfgParser.KeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Stalker2CfgParser.array_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_ref([NotNull] Stalker2CfgParser.Array_refContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Stalker2CfgParser.set_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_ref([NotNull] Stalker2CfgParser.Set_refContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Stalker2CfgParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] Stalker2CfgParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Stalker2CfgParser.struct_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_key([NotNull] Stalker2CfgParser.Struct_keyContext context);
}
